"use client";
import { useMemo, useState } from "react";
import { Search, SlidersHorizontal, X } from "lucide-react";
import { ProductCard } from "@/components/product-card";
import type { Product } from "@/lib/products";

export function ProductExplorer({products}:{products:Product[]}){
  const [query,setQuery]=useState("");const [type,setType]=useState("all");const [budget,setBudget]=useState(300);const [rating,setRating]=useState(0);const [sort,setSort]=useState("relevant");const [shown,setShown]=useState(24);
  const types=Array.from(new Set(products.map(p=>p.unterkategorie)));
  const filtered=useMemo(()=>products.filter(p=>(!query||`${p.marke} ${p.modellcode} ${p.titel}`.toLowerCase().includes(query.toLowerCase()))&&(type==="all"||p.unterkategorie===type)&&(!p.preisEUR||p.preisEUR<=budget)&&(!p.bewertung||p.bewertung>=rating)).sort((a,b)=>sort==="price-asc"?(a.preisEUR??9999)-(b.preisEUR??9999):sort==="price-desc"?(b.preisEUR??0)-(a.preisEUR??0):sort==="rating"?(b.bewertung??0)-(a.bewertung??0):(b.anzahlBewertungen??0)-(a.anzahlBewertungen??0)),[products,query,type,budget,rating,sort]);
  function reset(){setQuery("");setType("all");setBudget(300);setRating(0);setShown(24)}
  return <section className="inner-section shell explorer"><aside className="filter-panel"><div className="filter-title"><SlidersHorizontal/><h2>Filtern</h2><button onClick={reset}>Zurücksetzen</button></div><label>Suche<div className="search-field"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Marke oder Modell"/>{query&&<button onClick={()=>setQuery("")}><X/></button>}</div></label><label>Bauform<select value={type} onChange={e=>setType(e.target.value)}><option value="all">Alle Bauformen</option>{types.map(t=><option key={t}>{t}</option>)}</select></label><label>Budget bis <b>{budget} €</b><input type="range" min="50" max="300" step="10" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label><label>Bewertung mindestens<select value={rating} onChange={e=>setRating(Number(e.target.value))}><option value="0">Alle Bewertungen</option><option value="4">4,0 Sterne</option><option value="4.3">4,3 Sterne</option><option value="4.5">4,5 Sterne</option></select></label><div className="filter-note">Preise und Verfügbarkeit: Momentaufnahme vom 22.08.2026.</div></aside><div className="explorer-results"><div className="results-toolbar"><b>{filtered.length} Geräte gefunden</b><label>Sortieren <select value={sort} onChange={e=>setSort(e.target.value)}><option value="relevant">Relevanz</option><option value="rating">Bewertung</option><option value="price-asc">Preis aufsteigend</option><option value="price-desc">Preis absteigend</option></select></label></div><div className="product-grid explorer-grid">{filtered.slice(0,shown).map(p=><ProductCard product={p} key={p.asin}/>)}</div>{shown<filtered.length&&<button className="button secondary load-more" onClick={()=>setShown(shown+24)}>Weitere 24 anzeigen</button>}{filtered.length===0&&<div className="empty-state"><h2>Keine passende Kombination gefunden</h2><p>Lockere einen Filter oder starte den Finder für eine persönliche Empfehlung.</p><button className="button primary" onClick={reset}>Filter zurücksetzen</button></div>}</div></section>;
}
